const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
const GET_ALL_TYPES = "GET_ALL_TYPES";
const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
const ORDER_BY_NAME = "ORDER_BY_NAME"
const ORDER_BY_ATTACK = "ORDER_BY_ATTACK"
const FILTER_ALL = "FILTER_ALL"
const CLEAR_DETAIL = "CLEAR_DETAIL";
const CLEAR_ORDER = "CLEAR_ORDER"

export  { CLEAR_ORDER, CLEAR_DETAIL, FILTER_ALL, GET_ALL_POKEMONS, GET_ALL_TYPES, GET_POKEMON_BY_ID, GET_POKEMON_BY_NAME, ORDER_BY_NAME, ORDER_BY_ATTACK } ;